---
application:
  tittle: Trabajo Practico Numero 3

framework:
  host: 0.0.0.0
  port: 8080
  debug: true
  reloader: true
  workers: 5

database:
  debug: false
  engine:
    provider: sqlite
    filename: sqlite.db

loader:
  medics:
    speciality:
      - pediatra
      - cardiologo
    name:
      - Santo
      - Pepe
    lastname:
      - Domingo
      - Rapo
    medicid:
      - 999999
      - 888888
  patients:
    data:
      dni:
        - 31541955
        - 31541954
      name:
        - Javier
        - Pedro
      lastname:
        - Pereyra
        - Pasculi
      secureid:
        - 'abc123456'
        - 'abc654321'
      email:
        - javier.pereyra183@gmail.com
        - pedro.zaraza@gmail.com
  user:
    data:
      name:
        - Javier
        - Santo
      lastname:
        - Pereyra
        - Domingo
      userid:
        - santo182
        - pepe182
      password:
        - abc123
        - abc123
      rol:
        - medic
        - medic
      medicid:
        - 999999
        - 888888
        

email:
  account: utnprogramacion3@gmail.com
  password: h51kolv3
  smtp: smtp.gmail.com
  port: 587
